name: control_user_design_df
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_redux: ^0.10.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  go_router: ^14.2.3
  http: ^1.2.2
  redux: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
